### ISSUE TITLE
Anyone having their scoreboard working?

### ISSUE THREAD

**Issue by WashCaps33** [mikemountain/nfl-led-scoreboard#27]
With preseason starting tonight, has anyone fired up their board?  Does it work?  I'm trying to get mine going and keep getting errors. 

Side question - is there a slack channel to post questions like these?

**Comment by mikemountain** [comment]
hey man, sorry about this - currently the board will only show your favourite team's matchup (the board is still in super-alpha because football makes me too annoyed to work on it sometimes)

if you set your favourite team in the config to PIT or DAL it'll work, but I'm working on something right now to fix this bug.

also, the logos are mis-sized and I need to fix that as well
